name: Wheel Lottery Picks

on:
  workflow_dispatch:
    inputs:
      tickets:
        description: Number of tickets to generate
        required: false
        default: "5"
      seed:
        description: Optional random seed
        required: false
        default: ""

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate picks
        run: |
          python scripts/wheel_picks.py --tickets "${{ github.event.inputs.tickets }}" $( [ -n "${{ github.event.inputs.seed }}" ] && echo --seed "${{ github.event.inputs.seed }}" )

      - name: Create PR with results
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(results): add wheel lottery picks"
          title: "chore(results): wheel lottery picks (tickets=${{ github.event.inputs.tickets }})"
          body: |
            Automated results generated by workflow run.
          branch: "bot/wheel-lottery-results-${{ github.run_id }}"
          base: ${{ github.ref_name }}
          add-paths: |
            results/**
